# Generated by Django 4.1.5 on 2023-01-20 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('house_number', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
            },
        ),
        migrations.CreateModel(
            name='Businessman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('debt_value', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Индивидуальный предприниматель',
                'verbose_name_plural': 'Индивидуальные предприниматели',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.address')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contacts', models.ManyToManyField(to='network.contact')),
                ('employees', models.ManyToManyField(to='network.employee')),
            ],
            options={
                'verbose_name': 'Завод',
                'verbose_name_plural': 'Заводы',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='RetailChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('debt_value', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contacts', models.ManyToManyField(to='network.contact')),
                ('employees', models.ManyToManyField(to='network.employee')),
                ('products', models.ManyToManyField(to='network.product')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.plant')),
            ],
            options={
                'verbose_name': 'Розничная сеть',
                'verbose_name_plural': 'Розничные сети',
            },
        ),
        migrations.AddField(
            model_name='plant',
            name='products',
            field=models.ManyToManyField(to='network.product'),
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('businessman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.businessman')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.plant')),
                ('retail_chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.retailchain')),
            ],
            options={
                'verbose_name': 'Сеть поставщиков',
                'verbose_name_plural': 'Сети поставщиков',
            },
        ),
        migrations.AddField(
            model_name='businessman',
            name='contacts',
            field=models.ManyToManyField(to='network.contact'),
        ),
        migrations.AddField(
            model_name='businessman',
            name='employees',
            field=models.ManyToManyField(to='network.employee'),
        ),
        migrations.AddField(
            model_name='businessman',
            name='products',
            field=models.ManyToManyField(to='network.product'),
        ),
        migrations.AddField(
            model_name='businessman',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.retailchain'),
        ),
    ]
