# Generated by Django 4.1.5 on 2023-01-18 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='house_number',
            field=models.PositiveIntegerField(),
        ),
    ]
