# Generated by Django 4.1.5 on 2023-01-19 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_remove_businessman_contacts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='debt_value',
        ),
    ]
