# Generated by Django 4.1.5 on 2023-01-18 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_alter_address_city_alter_address_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='network',
            old_name='factory',
            new_name='plant',
        ),
    ]
