# Generated by Django 4.1.5 on 2023-01-20 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_remove_plant_debt_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distributor',
            name='contacts',
        ),
        migrations.RemoveField(
            model_name='distributor',
            name='employees',
        ),
        migrations.RemoveField(
            model_name='distributor',
            name='products',
        ),
        migrations.RemoveField(
            model_name='distributor',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='network',
            name='dealership',
        ),
        migrations.RemoveField(
            model_name='network',
            name='distributor',
        ),
        migrations.AlterField(
            model_name='retailchain',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.plant'),
        ),
        migrations.DeleteModel(
            name='Dealership',
        ),
        migrations.DeleteModel(
            name='Distributor',
        ),
    ]
