# Generated by Django 4.1.5 on 2023-01-19 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_network_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessman',
            name='debt_currency',
        ),
        migrations.RemoveField(
            model_name='dealership',
            name='debt_currency',
        ),
        migrations.RemoveField(
            model_name='distributor',
            name='debt_currency',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='debt_currency',
        ),
        migrations.RemoveField(
            model_name='retailchain',
            name='debt_currency',
        ),
        migrations.AlterField(
            model_name='businessman',
            name='debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='dealership',
            name='debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='plant',
            name='debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='retailchain',
            name='debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
    ]
