# Generated by Django 4.1.5 on 2023-01-19 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_remove_businessman_debt_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessman',
            name='debt',
        ),
        migrations.RemoveField(
            model_name='dealership',
            name='debt',
        ),
        migrations.RemoveField(
            model_name='distributor',
            name='debt',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='debt',
        ),
        migrations.RemoveField(
            model_name='retailchain',
            name='debt',
        ),
    ]
