# Generated by Django 4.1.5 on 2023-01-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_remove_businessman_debt_remove_dealership_debt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessman',
            name='debt_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AddField(
            model_name='dealership',
            name='debt_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AddField(
            model_name='distributor',
            name='debt_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AddField(
            model_name='plant',
            name='debt_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AddField(
            model_name='retailchain',
            name='debt_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
    ]
